# Site settings
title: Your Site Title
description: Your site's description
baseurl: "" # The subpath of your site, e.g., /blog/
url: "https://username.github.io" # The base hostname & protocol for your site

# Build settings
theme: jekyll-theme-cayman # You can change this to a different Jekyll theme
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown and HTML settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Other settings
author: Your Name
